#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageJsonPath = join(__dirname, "../package.json");
const versionFilePath = join(__dirname, "../src/version.ts");

let packageJson;
try {
	packageJson = JSON.parse(readFileSync(packageJsonPath, "utf-8"));
} catch (err) {
	console.error(`Failed to read or parse package.json: ${err.message}`);
	process.exit(1);
}

const content = `// Auto-generated by scripts/generate-version.js - DO NOT EDIT
export const VERSION = "${packageJson.version}";
`;

try {
	writeFileSync(versionFilePath, content);
	console.log(`Generated src/version.ts with version ${packageJson.version}`);
} catch (err) {
	console.error(`Failed to write version file: ${err.message}`);
	process.exit(1);
}
